/** Wspólne dane: landing + portfolio (katalog.html). Grafiki sklepu: ./images/shop-druki/ (sync z Desktop/SHOPIFY, skrypt scripts/copy-shop-druki-images.mjs). */
window.PORTFOLIO_DATA = {
  /** Pełny URL zewnętrznej strony malarstwa; puste = karty bez linku (tylko podgląd). */
  PAINTINGS_PAGE: '',
  works: [
    { title: "Absolute Gravitas", href: "", technique: "linoryt", size: "50×50 cm", award: "Finał i wystawa XV Ogólnopolskiego Konkursu Grafiki im. Józefa Gielniaka, 2022, Jelenia Góra", image: "./images/shop-druki/absolute-gravitas.jpg" },
    { title: "Apocalypse", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/apocalypse.jpg" },
    { title: "Canyon Space", href: "", technique: "linoryt", size: "30×40 cm", image: "./images/shop-druki/canyon-space.jpg" },
    { title: "Cubic Space", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/cubic-space.jpg" },
    { title: "Cubic Space 3", href: "", technique: "linoryt", size: "55×75 cm", image: "./images/shop-druki/cubic-space-3.jpg" },
    { title: "Cubic Space 4", href: "", technique: "linoryt", size: "50×30 cm", image: "./images/shop-druki/cubic-space-4.jpg" },
    { title: "Cum vanitas", href: "", technique: "linoryt", size: "30×40 cm", image: "./images/shop-druki/cum-vanitas.jpg" },
    { title: "Dome", href: "", technique: "linoryt", size: "60×80 cm", image: "./images/shop-druki/dome.jpg" },
    { title: "Elatio in Nihilum", href: "", technique: "linoryt", size: "60×60 cm", award: "Finał i wystawa XV Ogólnopolskiego Konkursu Grafiki im. Józefa Gielniaka, 2022, Jelenia Góra", image: "./images/shop-druki/elatio-in-nihilum.jpg" },
    { title: "Entropy Space", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/entropy-space.jpg" },
    { title: "Entropy Space 2", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/entropy-space-2.jpg" },
    { title: "Falling Space", href: "", technique: "linoryt", size: "50×60 cm", image: "./images/shop-druki/falling-space.jpg" },
    { title: "Fate Vanity", href: "", technique: "linoryt", size: "30×40 cm", image: "./images/shop-druki/fate-vanity.jpg" },
    { title: "Footprint", href: "", technique: "linoryt", size: "48×63 cm", image: "./images/shop-druki/footprint.jpg" },
    { title: "Götterdämmerung", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/gotterdammerung.jpg" },
    { title: "Gravitas Inanis", href: "", technique: "linoryt", size: "30×40 cm", image: "./images/shop-druki/gravitas-inanis.jpg" },
    { title: "Inside Space", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/inside-space.jpg" },
    { title: "Interitus Fatum", href: "", technique: "linoryt", size: "50×70 cm", award: "Finał i wystawa Międzynarodowego Biennale Grafiki R.O.C., 2022, Tajpej", image: "./images/shop-druki/interitus-fatum.jpg" },
    { title: "Landing Space", href: "", technique: "linoryt", size: "50×66 cm", image: "./images/shop-druki/landing-space.jpg" },
    { title: "Umbra Gloriae", href: "", technique: "linoryt", size: "70×50 cm", image: "./images/shop-druki/laokoon.jpg" },
    { title: "Lost Pyramid", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/lost-pyramid.jpg" },
    { title: "Melancholy", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/melancholy.jpg" },
    { title: "Memory of Space", href: "", technique: "linoryt", size: "60×40 cm", image: "./images/shop-druki/memory-of-space.jpg" },
    { title: "Moon Space", href: "", technique: "linoryt", size: "30×40 cm", image: "./images/shop-druki/moon-space.jpg" },
    { title: "On the Moon 1", href: "", technique: "linoryt", size: "45×37 cm", image: "./images/shop-druki/on-the-moon-1.png" },
    { title: "On the Moon 2", href: "", technique: "linoryt", size: "50×50 cm", image: "./images/shop-druki/on-the-moon-2.jpg" },
    { title: "Outward Search", href: "", technique: "linoryt", size: "50×50 cm", image: "./images/shop-druki/outward-search.jpg" },
    { title: "Pyramid Space", href: "", technique: "linoryt", size: "50×50 cm", image: "./images/shop-druki/pyramid-space.jpg" },
    { title: "Pyramid Space 3–2", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/pyramid-space-3-2.jpg" },
    { title: "Pyra", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/pyra.jpg" },
    { title: "Solium Spatium", href: "", technique: "linoryt", size: "70×50 cm", image: "./images/shop-druki/solium-spatium.jpg" },
    { title: "Space Hole", href: "", technique: "linoryt", size: "50×66 cm", image: "./images/shop-druki/space-hole.jpg" },
    { title: "Square Space", href: "", technique: "linoryt", size: "50×70 cm", image: "./images/shop-druki/square-space.jpg" },
    { title: "Stańczyki", subtitle: "„Stańczyki, night”", href: "", technique: "linoryt", size: "65×50 cm", image: "./images/shop-druki/stanczyki.jpg" },
    { title: "Tempus Forma", href: "", technique: "linoryt", size: "60×60 cm", image: "./images/shop-druki/tempus-forma.jpg" },
    { title: "Triangle Space", href: "", technique: "linoryt", size: "50×66 cm", image: "./images/shop-druki/triangle-space.jpg" },
    { title: "Ultimus Spiritus", href: "", technique: "linoryt", size: "60×40 cm", image: "./images/shop-druki/ultimus-spiritus.jpg" },
    { title: "Vanum Spurt", href: "", technique: "linoryt", size: "60×80 cm", image: "./images/shop-druki/vanum-spurt.jpg" },
    { title: "Xiega", href: "", technique: "linoryt", size: "46×63 cm", image: "./images/shop-druki/xiega.jpg" },
    { title: "Zen Space", href: "", technique: "linoryt", size: "50×50 cm", image: "./images/shop-druki/zen-space.jpg" },
  ],
  paintings: [
    { title: "Elatio in nihil", size: "120×90 cm", image: "./images/2023/03/elatioinnihilum1500-1.jpg" },
    { title: "Cum vanitas", size: "90×90 cm", image: "./images/2023/03/cumvanitas1500-4.jpg" },
    { title: "Absolute gravitas", size: "90×130 cm", image: "./images/2023/04/AbsoluteGravitas3.jpg" },
    { title: "Vanum spurt", size: "90×90 cm", image: "./images/2023/07/vanum-spurt.jpg" },
    { title: "Gravitas inanis", size: "90×120 cm", image: "./images/2023/11/gravitas-inanis-WWW.jpg" },
    { title: "Interitus Fatum", size: "120×90 cm", image: "./images/2024/03/InteritusFatum.jpg" },
    { title: "Götterdämmerung", size: "120×90 cm", image: "./images/2024/03/gotterdamerung-copy-1.jpg" },
    { title: "Oblitus Spatium", size: "90×120 cm", image: "./images/2024/05/oblitus-spatium-www.jpg" },
    { title: "Galatea", size: "90×70 cm", image: "./images/2024/09/Galateasmall-2.jpg" },
    { title: "Finis vitae", size: "90×70 cm", image: "./images/2024/11/Finis-vitae.jpg" },
    { title: "Relicta saecularia", size: "75×60 cm", image: "./images/2025/06/relicta-saecularia75x60.jpg" },
    { title: "Aquila nebula", size: "61×50 cm", image: "./images/2025/01/Aquila-nebula.jpg" },
    { title: "Equus caput nebula", size: "61×50 cm", image: "./images/2025/02/equus-caput-nebula.jpg" },
    { title: "Solium spatium", size: "75×60 cm", image: "./images/2025/02/Solium-Spatium-2.jpg" },
    { title: "Olympus", size: "65×55 cm", image: "./images/2025/03/OlymAE-1.png" },
    { title: "Lacoon", size: "65×55 cm", image: "./images/2025/04/lacoon-1.jpg" },
    { title: "Inertem tempus", size: "73×92 cm", image: "./images/2025/05/inertem-tempus.jpg" },
      { title: "Memoria spatialis", size: "80×60 cm", sold: true, image: "./images/2025/06/memoria-spatialis.jpg" },
    { title: "Intra spatium", size: "120×100 cm", image: "./images/2025/06/Interspatium.jpg" },
      { title: "Melancholia", size: "80×60 cm", sold: true, image: "./images/2026/02/Melacholia5.jpg" },
    { title: "Umbra gloriae", size: "80×60 cm", image: "./images/2025/08/Umbra-gloriae.jpg" },
    { title: "Oumuamua", size: "73×100 cm", image: "./images/2025/09/Oumuamua.jpg" },
    { title: "Semen fati", size: "73×100 cm", image: "./images/2025/12/semen-fati.jpg" },
    { title: "Lumen vacui", size: "80×80 cm", image: "./images/2025/12/Lumen-vacui.jpg" },
    { title: "Illuminatio", size: "80×70 cm", image: "./images/2026/04/IlluminatioFull.jpg" },
    { title: "Ascensus", size: "65×82 cm", image: "./images/2026/01/Ascensus.jpg" },
    { title: "Solitudo", size: "60×90 cm", image: "./images/2026/02/Solitudo.jpg" },
    { title: "Victoria Pyrrhica", size: "90×70 cm · 2026", image: "./images/2026/04/Victoria-Pyrrhica.jpg" },
  ],
};
