/** Wspólne dane: landing + portfolio (katalog.html). Edytuj tutaj. */
window.PORTFOLIO_DATA = {
  /** Pełny URL zewnętrznej strony malarstwa; puste = karty bez linku (tylko podgląd). */
  PAINTINGS_PAGE: '',
  works: [
      { title: "Stańczyki", subtitle: "„Stańczyki, night”", href: "", technique: "linoryt", size: "65×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2026/03/Sta-czyki0.jpg" },
      { title: "Ultimus Spiritus", href: "", technique: "linoryt", size: "60×40 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/11/Ultimus-spiritus.jpg" },
      { title: "Laokoon", href: "", technique: "linoryt", size: "70×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/11/UmbraGloriae.jpg" },
      { title: "Solium Spatium", href: "", technique: "linoryt", size: "70×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/02/solium-spatium.jpg" },
      { title: "Tempus Forma", href: "", technique: "linoryt", size: "60×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/12/tempus-forma-1.jpg" },
      { title: "Galatea", href: "", technique: "linoryt", size: "100×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/11/galatea-3.jpg" },
      { title: "Lost Pyramid", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/08/Lost-pyramid2.jpg" },
      { title: "Melancholy", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/01/melanholy.png" },
      { title: "Vanum Spurt", href: "", technique: "linoryt", size: "60×80 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/11/vanumspurt-3.png" },
      { title: "Elatio in Nihilum", href: "", technique: "linoryt", size: "60×60 cm", award: "Finał i wystawa XV Ogólnopolskiego Konkursu Grafiki im. Józefa Gielniaka, 2022, Jelenia Góra", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/06/Elatio.jpg" },
      { title: "Absolute Gravitas", href: "", technique: "linoryt", size: "50×50 cm", award: "Finał i wystawa XV Ogólnopolskiego Konkursu Grafiki im. Józefa Gielniaka, 2022, Jelenia Góra", image: "https://linocut.andrzejratajczyk.pl/content/images/2022/05/absolutefgravity.jpg" },
      { title: "Interitus Fatum", href: "", technique: "linoryt", size: "50×70 cm", award: "Finał i wystawa Międzynarodowego Biennale Grafiki R.O.C., 2022, Tajpej", image: "https://linocut.andrzejratajczyk.pl/content/images/2022/03/Interitus-fatum.jpg" },
      { title: "Memory Space", href: "", technique: "linoryt", size: "50×70 cm", award: "Finał i wystawa XI Polskiego Triennale Grafiki, 2021, Katowice", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/04/memory-of-space.jpg" },
      { title: "Gravitas Inanis", href: "", technique: "linoryt", size: "30×40 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2022/01/cum-vanitas.jpg" },
      { title: "Fate Vanity", href: "", technique: "linoryt", size: "30×40 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2021/11/fatevanity-4.jpg" },
      { title: "Götterdämmerung", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2021/11/gotterdammerung-1.jpg" },
      { title: "Dome", href: "", technique: "linoryt", size: "60×80 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2021/10/Dome-of-imaginations1.jpg" },
      { title: "F", href: "", technique: "linoryt", size: "82×52 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/10/Forgotten-space-cut.jpg" },
      { title: "Outward Search", href: "", technique: "linoryt", size: "50×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2021/10/Outward-search-2.jpg" },
      { title: "Memory of Space", href: "", technique: "linoryt", size: "60×40 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/04/gravitas-inanis-copy.jpg" },
      { title: "Zen Space", href: "", technique: "linoryt", size: "50×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2020/11/zen-space-10.jpg" },
      { title: "Inside Space", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/INSIDE-SPACE.jpg" },
      { title: "Mirror Space", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/mirror-space.jpg" },
      { title: "Entropy Space 2", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/EntropySpace2.jpg" },
      { title: "Entropy Space", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/EntropySpace.jpg" },
      { title: "Crying Space", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/cryingspace.jpg" },
      { title: "Moon Space", href: "", technique: "linoryt", size: "30×40 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2020/03/moonspace.jpg" },
      { title: "Canyon Space", href: "", technique: "linoryt", size: "30×40 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2020/03/-canyonspace-1.jpg" },
      { title: "Diamond Space", href: "", technique: "linoryt", size: "25×35 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2020/01/pyramidspace4-1.jpg" },
      { title: "Cubic Space 5", href: "", technique: "linoryt", size: "25×35 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2020/01/cubicspace5.jpg" },
      { title: "Cubic Space 4", href: "", technique: "linoryt", size: "50×30 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2020/01/cubicspace4-3.jpg" },
      { title: "Pyramid Space 3–2", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/pyramidspace3.jpg" },
      { title: "Cubic Space 3", href: "", technique: "linoryt", size: "55×75 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/cubicspace3.jpg" },
      { title: "Falling Space", href: "", technique: "linoryt", size: "50×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/Faallingspace.jpg" },
      { title: "Xiega", href: "", technique: "linoryt", size: "46×63 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/Xi-ga.jpg" },
      { title: "Pyra", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/pyramidspace.jpg" },
      { title: "Cubic Space 2", href: "", technique: "linoryt", size: "30×30 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2019/06/cubicspace2_print-30x30_-paper-48x48.jpg" },
      { title: "Cubic Space", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/cubicspace.jpg" },
      { title: "On the Moon 1", href: "", technique: "linoryt", size: "45×37 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/onthemoon-1-1.jpg" },
      { title: "Plural Melts — Dunmore Caves (Yvonne Lambert)", href: "", technique: "linoryt", size: "50×70 cm", note: "Szczegóły: artviewer.org — wystawa", image: "https://linocut.andrzejratajczyk.pl/content/images/2019/02/9-1.jpg" },
      { title: "Apocalypse", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/apokalipsa.jpg" },
      { title: "Square Space", href: "", technique: "linoryt", size: "50×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/squarespace.jpg" },
      { title: "Space Hole", href: "", technique: "linoryt", size: "50×66 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/Holespace-1.jpg" },
      { title: "Triangle Space", href: "", technique: "linoryt", size: "50×66 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/Trianglespace.jpg" },
      { title: "Landing Space", href: "", technique: "linoryt", size: "50×66 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/landingspace.jpg" },
      { title: "On the Moon 2", href: "", technique: "linoryt", size: "50×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/onthemoon2.jpg" },
      { title: "Footprint", href: "", technique: "linoryt", size: "48×63 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/Footprint.jpg" },
      { title: "Pyramid Space", href: "", technique: "linoryt", size: "50×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/10/pyramid-2.jpg" },
    ],
  paintings: [
      { title: "Elatio in nihil", size: "120×90 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/elatioinnihilum1500-1.jpg" },
      { title: "Cum vanitas", size: "90×90 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/03/cumvanitas1500-4.jpg" },
      { title: "Absolute gravitas", size: "90×130 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/04/AbsoluteGravitas3.jpg" },
      { title: "Vanum spurt", size: "90×90 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/07/vanum-spurt.jpg" },
      { title: "Gravitas inanis", size: "90×120 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2023/11/gravitas-inanis-WWW.jpg" },
      { title: "Interitus Fatum", size: "120×90 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/03/InteritusFatum.jpg" },
      { title: "Götterdämmerung", size: "120×90 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/03/gotterdamerung-copy-1.jpg" },
      { title: "Oblitus Spatium", size: "90×120 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/05/oblitus-spatium-www.jpg" },
      { title: "Galatea", size: "90×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/09/Galateasmall-2.jpg" },
      { title: "Finis vitae", size: "90×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2024/11/Finis-vitae.jpg" },
      { title: "Relicta saecularia", size: "75×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/06/relicta-saecularia75x60.jpg" },
      { title: "Aquila nebula", size: "61×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/01/Aquila-nebula.jpg" },
      { title: "Equus caput nebula", size: "61×50 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/02/equus-caput-nebula.jpg" },
      { title: "Solium spatium", size: "75×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/02/Solium-Spatium-2.jpg" },
      { title: "Olympus", size: "65×55 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/03/OlymAE-1.png" },
      { title: "Lacoon", size: "65×55 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/04/lacoon-1.jpg" },
      { title: "Inertem tempus", size: "73×92 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/05/inertem-tempus.jpg" },
      { title: "Memoria spatialis", size: "80×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/06/memoria-spatialis.jpg" },
      { title: "Intra spatium", size: "120×100 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/06/Interspatium.jpg" },
      { title: "Melancholia", size: "80×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2026/02/Melacholia5.jpg", note: "SOLD" },
      { title: "Umbra gloriae", size: "80×60 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/08/Umbra-gloriae.jpg" },
      { title: "Oumuamua", size: "73×100 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/09/Oumuamua.jpg" },
      { title: "Semen fati", size: "73×100 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/12/semen-fati.jpg" },
      { title: "Lumen vacui", size: "80×80 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2025/12/Lumen-vacui.jpg" },
      { title: "Illuminatio", size: "80×70 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2026/04/IlluminatioFull.jpg" },
      { title: "Ascensus", size: "65×82 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2026/01/Ascensus.jpg" },
      { title: "Solitudo", size: "60×90 cm", image: "https://linocut.andrzejratajczyk.pl/content/images/2026/02/Solitudo.jpg" },
      { title: "Victoria Pyrrhica", size: "90×70 cm · 2026", image: "https://linocut.andrzejratajczyk.pl/content/images/2026/04/Victoria-Pyrrhica.jpg" },
    ],
};
